name: flutter_web
publish_to: none

environment:
  sdk: any

dependencies:
  flutter_web_ui: any
  collection: any
  meta: any
  vector_math: any
  typed_data: any

dev_dependencies:
  flutter_web_test: any
  mockito: any
  test: any
  path: any
  quiver: any

dependency_overrides:
  flutter_web_test:
    path: ../flutter_web_test
  flutter_web_ui:
    path: ../flutter_web_ui
