name: flutter_web_test
publish_to: none

environment:
  sdk: any

dependencies:
  flutter_web: any
  collection: any
  html: any
  intl: any
  meta: any
  quiver: any
  vector_math: any
  test: any

dependency_overrides:
  flutter_web:
    path: ../flutter_web
  flutter_web_ui:
    path: ../flutter_web_ui
